CREATE TABLE `user` (
  `user_id` int(11) NOT NULL AUTO_INCREMENT COMMENT '用户唯一id',
  `upper_user_id` int(11) DEFAULT NULL COMMENT '上级id',
  `user_nickname` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '用户昵称',
  `user_protrait_pic` varchar(256) DEFAULT NULL COMMENT '用户头像',
  `phone_number` varchar(32) DEFAULT NULL COMMENT '电话号码',
  `open_id` varchar(32) DEFAULT NULL COMMENT '微信openid',
  `password` varchar(32) DEFAULT NULL COMMENT '登录后台密码',
  `qq_number` varchar(16) DEFAULT NULL COMMENT 'QQ号',
  `wechat_number` varchar(32) DEFAULT NULL COMMENT '微信号',
  `role` int(11) DEFAULT NULL COMMENT '角色',
  `email` varchar(64) DEFAULT NULL COMMENT '邮箱',
  `withdraw_money` float(11,2) DEFAULT NULL COMMENT '已提现金额',
  `flow_money` float(11,2) DEFAULT NULL COMMENT '可支配金额',
  `pending_money` float(11,2) DEFAULT NULL COMMENT '待结算金额',
  `company_name` varchar(255) DEFAULT NULL COMMENT '公司名',
  `legal_person_name` varchar(255) DEFAULT NULL COMMENT '真实姓名',
  `lp_idcard_front_pic` varchar(256) DEFAULT NULL COMMENT '身份证正面照',
  `lp_idcard_back_pic` varchar(256) DEFAULT NULL COMMENT '身份证反面照',
  `lp_handheld_idcard_pic` varchar(256) DEFAULT NULL COMMENT '手持身份证照',
  `business_licence_number` varchar(128) DEFAULT NULL COMMENT '营业执照号',
  `business_licence_pic` varchar(256) DEFAULT NULL COMMENT '营业执照',
  `logo_pic` varchar(256) DEFAULT NULL COMMENT '公司logo',
  `province_id` char(128) DEFAULT NULL COMMENT '省（引用address表）',
  `city_id` char(128) DEFAULT NULL COMMENT '市（引用address表）',
  `area_id` char(128) DEFAULT NULL COMMENT '区（引用address表）',
  `company_address_detail` varchar(256) DEFAULT NULL COMMENT '详细地址',
  `salesman_work_certify` varchar(256) DEFAULT NULL COMMENT '业务员工作证明',
  `jcv` varchar(256) DEFAULT NULL COMMENT '厂区实景图',
  `check_status` int(11) DEFAULT NULL COMMENT '审核状态',
  `apply_id` int(11) DEFAULT NULL COMMENT '认证id（引用certification_application表）',
  `follow_time` timestamp NULL DEFAULT NULL COMMENT '关注时间',
  `qr_code_pic` varchar(256) DEFAULT NULL COMMENT '微信二维码（自己上传的）',
  `short_company_name` varchar(64) DEFAULT NULL COMMENT '公司简称',
  `salesman_id` int(11) DEFAULT NULL COMMENT '门市业务员id',
  `spread_qr_code_pic` varchar(255) DEFAULT NULL COMMENT '推广二维码',
  `longitude` varchar(128) DEFAULT NULL COMMENT '经度',
  `latitude` varchar(128) DEFAULT NULL COMMENT '纬度',
  `new_qr_code` varchar(256) DEFAULT NULL COMMENT '推广二维码，带个人信息',
  `union_id` varchar(128) DEFAULT NULL COMMENT '微信union_id',
  `person_qr_code` varchar(256) DEFAULT NULL COMMENT '每日产品推广二维码',
  `user_identical_code` varchar(32) DEFAULT NULL COMMENT '用户编码（标在货物上，方便发货）',
  `information_phone` varchar(64) DEFAULT NULL COMMENT '联系电话',
  `we_app_open_id` varchar(64) DEFAULT NULL COMMENT '小程序open_id',
  `rent_visit_time` timestamp NULL DEFAULT NULL COMMENT '最近访问时间',
  `spread_code_generate_time` timestamp NULL DEFAULT NULL COMMENT '推广二维码生成时间',
  `agency_discount` float(11,2) DEFAULT NULL COMMENT '折扣图数额',
  `discount_title` varchar(256) DEFAULT NULL COMMENT '折扣图文字',
  `welcome_title` varchar(255) DEFAULT NULL COMMENT '欢迎页文字',
  `welcome_pic` varchar(256) DEFAULT NULL COMMENT '欢迎页图片',
  `lamp_selection_login` int(11) DEFAULT NULL COMMENT '配灯系统登陆权限',
  `is_concern` int(11) DEFAULT NULL COMMENT '是否关注平台',
  `wechat_pay_qr_code` varchar(255) DEFAULT NULL COMMENT '微信支付二维码，配灯系统显示',
  `alipay_qr_code` varchar(255) DEFAULT NULL COMMENT '支付宝支付二维码，配灯系统显示',
  `manage_role` int(11) DEFAULT NULL,
  `purchase_money` float(11,2) DEFAULT NULL,
  `abbreviation` varchar(255) DEFAULT NULL,
  `abbrevivation` varchar(255) DEFAULT NULL,
  `agent_commision_percent` float DEFAULT NULL,
  `company_brief` varchar(255) DEFAULT NULL,
  `contact` varchar(255) DEFAULT NULL,
  `contact_person` varchar(255) DEFAULT NULL,
  `free_post_require` float DEFAULT NULL,
  `return_address_id` int(11) DEFAULT NULL,
  `service_account` varchar(255) DEFAULT NULL,
  `user_status` int(11) DEFAULT NULL,
  `wechat_scene` int(11) DEFAULT NULL,
  PRIMARY KEY (`user_id`)
) ENGINE=MyISAM AUTO_INCREMENT=42104 DEFAULT CHARSET=utf8 COMMENT='salesman_id栏原本用于记录厂家业务员，现在改为记录门市业务员id';